[
  :account_account_status,
  :account_api_key_info,
  :char_wallet_transactions,
  :char_wallet_journal,
  :char_standings,
  :char_skill_queue,
  :char_medals,
  :char_market_orders,
  :char_mail_messages,
  :char_contact_list,
  :char_character_sheet,
  :char_account_balance
]

[
  :char_contracts,
  :char_upcoming_calendar_events,
  :char_mailing_lists,
  :char_industry_jobs,
  :char_contact_notifications,
]
